project:
  type: book
  output-dir: docs
  # resources: 
  #   -slides/**
  # pre-render: 
  # - bash setup_submodules.sh

book:
  title: "Larch 414: Planting Design for Ecological Performance (Spring 2027)"
  author: "Travis Flohr, Ph.D."
  date: "01/01/2027"
  chapters:
    - index.qmd
    - 01_core_plant_concepts.qmd

  sidebar:
    title: Larch 414 Course Content
    search: true
    collapse-level: 2

number-sections: true
crossref:
  chapters: true

bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 3
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt