### Departmental, School, and University Policies 
All departmental and school studio/building policies are in effect. 

### Communication Policy
Our official mode of communication in this class is through Canvas. Course-wide communication will be via Course Announcements. Personal communication between the teaching, and students will be via **Canvas Inbox**. All communication shall be respectful and professional. It is the student’s responsibility to check Canvas frequently. All technology troubleshooting questions should be directed to the appropriate **Canvas Discussion Board**. The teaching team will moderate discussion board posts and involve the faculty as needed. 
	
Before each field class, I will monitor the weather closely using local weather reports. Field classes will be held during good weather and when light rain is forecasted. **Dress accordingly!** **If the weather is predicted to be stormy and consistently wet during class time, I will post a Canvas announcement to the whole class** to opt for “Plan B,” either to meet on Zoom or in our classroom space. **The announcement may be sent the evening before or right up to about noon on the day of class. WATCH FOR MY CANVAS ANNOUNCEMENTS!**. 

### Weather-based Class Delays and Cancellation Policy 
For university-related early dismissals or cancellations, please refer to [http://news.psu.edu/story/333863/2014/11/10/campus-life/when-winter-weather-strikes-resources-university-park-community.](http://news.psu.edu/story/333863/2014/11/10/campus-life/when-winter-weather-strikes-resources-university-park-community){target="_blank"} For course-specific changes in scheduling or meeting requirements, see the “Bad Weather” information provided above. 

### Submission Policy
All projects and exercises must be submitted by the deadlines indicated in the course schedule. Incomplete assignments should be submitted by the deadline and will be graded as is. Students seeking an exception due to extenuating circumstances should message the faculty via Canvas before the deadline. **Late submissions** are strongly discouraged. **A deduction of one full letter grade** (e.g., B+ to C+) will be applied for each of the **first two 24-hour periods of unexcused lateness** beyond the deadline. **Submissions will not be accepted beyond 48 hours after the deadline and will receive 0 points (0%)**. 

### Engagement and Attendance Policy
As a core part of the professional curriculum, attendance is mandatory and will be recorded. If we have any Zoom lectures, they will be no different from face-to-face lectures in that we expect your timely attendance. Class time (face-to-face or virtual) is intended to achieve the progress necessary to complete this course successfully. Since we have just two weekly classes, we expect your engaged and productive presence for the entire class period.
	
If you cannot attend due to extenuating circumstances, you must provide the instructors with prior notification and the appropriate reasons. **If you have any cold, flu, or COVID-19-like symptoms, please stay home and/or isolate as appropriate.** **It is the student's responsibility to communicate via Canvas with faculty regarding absences and to make up missing work within the unexcused late period noted below.**
	
Inconsistent attendance, repeated lateness to class, or lack of progress and engagement during class may reduce the work grade for that assignment. Also, **a pattern of unexcused absence or tardiness may result in a reduction in your grade.** Note that we consider a student's inattentive presence during a lecture disengaged and, thus, effectively absent.
	
Finally, university-level class attendance policies apply. For more information, see: [https://undergrad.psu.edu/aappm/42-00-class-attendance.html.](https://senate.psu.edu/students/policies-and-rules-for-undergraduate-students/42-00-acquisition-of-credit/#:~:text=42%2D27%20Class-,Attendance,-Regular%20class%20attendance){target="_blank"}

**If you cannot attend due to illness or extenuating circumstances, Canvas message the teaching team promptly.** If you are seriously ill, notify the teaching team as soon as possible or ask a friend to do so on your behalf. **If you miss a Plant Walk, we expect you’ll catch up on your own** by visiting the site and finding/studying the designated plants for that session so that you’re prepared to take the associated quiz at the same time as your peers. If you must miss class due to activities in another class (e.g., a field trip), you must inform the instructional team promptly, well before class. Specifically, **beyond two (2) unexcused absences**, the student may receive a 2% reduction in an assignment grade for each subsequent unexcused absence. More generally, inconsistent attendance, a record of lateness, or a pattern of lack of progress or engagement during class or fieldwork may result in a significant grade reduction.



### Academic Integrity and Misconduct
We urge you to promise not to cheat on quizzes or plagiarize during the semester. Why? Because the only true road to professional and personal success is to be honest and embrace academic and personal integrity. When you learn honestly, you learn the material properly, and you feel good about yourself as a human being. **Evidence of cheating on a quiz or plagiarism on an assignment will result in a zero (0%) grade for the assignment in question, an additional final course grade reduction, and possibly, depending on severity, course failure and academic sanction.** If you have any doubts or questions about what constitutes cheating or academic misconduct, please do not hesitate to talk with the teaching team.

We will adhere to all academic integrity policies in this course. According to the University, academic integrity "is the pursuit of scholarly activity in an open, honest, and responsible manner (Penn State University, 2024)." Dishonesty and plagiarism are wrong and will result in academic sanctions. We will abide by university policy. For more information, see [https://bulletins.psu.edu/undergraduate/general-information/academic-information/student-rights-responsibilities/academic-integrity/.](https://bulletins.psu.edu/undergraduate/general-information/academic-information/student-rights-responsibilities/academic-integrity/.){target="_blank"}  If you plagiarize any portion of an assignment, you will receive 0 points (0%) for the assignment. When in doubt, seek advice from the course teaching team. 

### Inclusivity, Justice, Collaboration, and Accommodations
In the spirit of shared humanity and concern for our community and world, we recognize that our learning activities and design solutions can either support or disadvantage groups of people and individuals. We value critical reasoning, self-reflection, imagination, empathy, inclusivity, and collaboration. We disavow racism and all other systemic patterns of prejudice, including speech or actions that attempt to silence, threaten, degrade, disadvantage, or displace groups and individuals. We advocate for social and environmental justice and inclusive communities and places as we work toward an equitable, democratic, and sustainable society. As future landscape architects, you have the opportunity and responsibility to create and define civic spaces and landscapes that are welcoming to all people and address plant-related societal issues (e.g., ecosystem service equity and biodiversity collapse). We will support and enforce all nondiscrimination and harassment policies. For more information, see [https://guru.psu.edu/policies/AD85.html.](https://guru.psu.edu/policies/AD85.html){target="_blank"}

### Educational Equity   
Consistent with University Policy AD29, students who believe they have experienced or observed a hate crime, an act of intolerance, discrimination, or harassment that occurs at Penn State are urged to report these incidents. Refer to http://equity.psu.edu/reportbias/.

### Indigenous Lands Statement   
As landscape stewards and advocates for both restorative justice and the environment, we acknowledge that the Stuckeman School rests on the ancestral lands of the Erie, Haudenosaunee, Lenape, Shawnee, Susquehannock, and Wahzhazhe Nations. As a land grant institution, we acknowledge and honor the traditional caretakers of these lands and strive to understand and model their responsible stewardship. We also acknowledge the longer history of these lands and our place in that history. Penn State's land grant was funded by selling land taken from 112 tribal nations in 50 land cessions across 16 states. This injustice has yet to be openly acknowledged by Penn State, much less reconciled.

### Penn State Values and Student Code of Conduct
We expect all students to conduct themselves in accordance with the University's Code of Conduct. For details, see [https://studentaffairs.psu.edu/support-safety-conduct/student-conduct/code-conduct.](https://studentaffairs.psu.edu/support-safety-conduct/student-conduct/code-conduct){target="_blank"} Please follow the core Penn State values of Integrity, Respect, Responsibility, Discovery, Excellence, and Community.

## Support

### Counseling & Psychological Services Resources
Counseling and psychological service resources are available to all students. If you need support, be sure to use these resources. For more information, see [http://studentaffairs.psu.edu/counseling/.](http://studentaffairs.psu.edu/counseling/){target="_blank"}

### Accommodations
Students with disabilities are welcomed into Penn State and SALA educational programs. If you need modifications or reasonable accommodations in this course due to a disability, contact the Office for Disability Services (ODS) and inform the course faculty. ODS is located at 116 Boucke Building. For more information, see [https://equity.psu.edu/offices/student-disability-resources.](https://equity.psu.edu/offices/student-disability-resources){target="_blank} Please provide accommodation requests and documentation to the course faculty at the beginning of the course so we can best support you.

## Changes and Updates
The syllabus, schedule, project statements, lectures, and supporting materials are subject to change and are copyrighted. Faculty will promptly communicate revisions verbally and via Canvas announcements. 