As most practicing landscape architects will attest, getting to know plants requires personal dedication to researching, detailing, implementing, and managing plants, soils, and their landscape contexts through time – in practice. While this studio presents course material via regular lectures and plant walks, background learning is necessary through **independent research**. I expect and encourage you to take the initiative to develop your plant knowledge rigorously. You are becoming a Landscape Architect; **plants are your thing**. Get into a habit of regularly using resources available in the SALA library and the many good online sources. The citations below provide a solid base of information. Note that none are required purchases; however, many students have purchased them as they have proven invaluable in their landscape architecture careers.

## Plant Nativity

Whether plants are ‘native’ (indigenous) to a spot depends on spatial scale and timing. One could say that all plants throughout time are native to planet Earth. Landscape Architects often use a too-large reference scale when designating a plant’s native.’ For example, we might say that the Sweet gum tree (*Liquidambar styraciflua*) is native to Happy Valley; however, it’s only found growing naturally in extreme SE Pennsylvania and is much more common in the U.S. Southeast. Similarly, local ecosystem context matters; Black gum (*Nyssa sylvatica*) is native to central PA, but it’s usually only found growing naturally up on the high ridges, away from the limestone valleys. We’ll discuss notions of plant nativity throughout the semester.

**I acknowledge that climate change will increasingly challenge our concepts of local plant nativity due to rapid and extreme shifts in hardiness zones, extreme weather, and climate, suggesting an intelligent, nuanced, and well-researched approach to plants is necessary to ensure the continued habitability of our planet. This also implies you must wrestle with the question, “What role should you play in assisted plant migration?”**

## The 70:30 Native/Introduced Plant Guideline

I admit to favoring native plants—that is, plants that are indigenous to the region in which they grow. Consider Narango et al. (2018), who found that:

> “Nonnative plants lack an evolutionary history with native fauna and support insect communities that are less abundant and diverse, and this may change food availability for vertebrate consumers…. **We found that insectivorous birds could be sustained only if nonnative plants accounted for \<30% of plant biomass.** **Our results demonstrate that nonnative plants reduce habitat quality** for insectivorous birds, and **restoration of human-dominated areas should prioritize native plants to support local food webs.**”

Although landscape architects increasingly favor native species, introduced plants have their place—we will discuss this at greater length. In contexts like ornamental gardens and tough urban conditions, non-native and cultivated varieties (“cultivars”) may be the best choice. So, let’s be guided by the \<30% nonnative biomass research.

## Plant Nomenclature 

::: {.callout-tip}
## Hint

The plant nomenclature information here will be a core part of projects submitted in all plant related courses because clear and accurate communication of plant names is critical to ensure your designs are implemented correctly
::: 

Consistent and accurate plant **nomenclature**—the formal, **scientific naming of plants**—is vital to successful and timely design, project implementation, and ongoing management of designed and natural landscapes. The botanical (i.e., scientific) names of plants are mostly Latin-inspired but are sometimes of Greek origin. They are the **lingua franca** of the landscape and horticulture industries. When you are fluent in plant names, you gain credibility as a professional, plant visualization becomes easier, and your designs become more articulate and competent.
	
In this course, we will use both the scientific and Common plant names—usually both when referring to a specific plant. We will use a species' full, binomial name, that is, both the **genus** and the specific epithet (**specie**). Protocols are documented in @tbl-nomenclature_conventions. 

| Nomenclature rule/convention                    | Scientific name       |Common name    |
|:------------------------------------------------|:---------------------|:----------------------|
|***Naming Basics***|
|Scientific name is always in italics; Common name is always in non-italics | *Quercus alba* |White oak |
|At the simplest classification level, Scientific names are binomial: the generic name (genus) begins with upper case, while the specific name (species, or epithet) remains all lower case | *Quercus alba* |White oak |
|The Common name specie is capitalized (e.g. White), while the genus is not (e.g. oak)| *Quercus alba* |White oak |
|Scientific name usually precedes Common name, for example, in Plant Schedules as part of contract documents |*Quercus alba* |White oak |
|***Cultivar Conventions***|
|The cultivar part of Scientific names are i) not italicized, ii) are set in single quotes, and iii) are capitalized | *Acer rubrum* ‘Autumn Blaze’ | Autumn Blaze red maple|
|The cultivar part of the Common name is capitalized, while the genus and specie are not.|*Acer rubrum* ‘Autumn Blaze’ | Autumn Blaze red maple|
|***Formal or Place Naming Conventions***|
|If the Common name includes a formal or place name, the formal name remains capitalized |*Amelanchier laevis* ‘Cumulus’ |Cumulus Allegheny serviceberry |
|***Unknown parentage***|
|At times, the parentage of cultivars is unclear, in which case just the Scientific genus and the cultivar names are shown |*Heuchera* ‘Caramel’ |Caramel coral bells|
|***Hybrids***|
|Hybrids do not show the Scientific species name of their 2 parent species, but have their own specific epithet, preceded by an “x” to denote hybrid status |*Gaillardia* x *grandiflora* |Large-flowered gaillardia|
|***Bontanist***|
|Scientific publications will often include the first initial of the surname of the botanist who discovered/named the plant. However, our profession does not show this abbreviation on design or contract documents (“L.” denotes the taxonomist Carl Linnaeus, who first described this tree). | *Quercus rubra* L.|
|***Specie and Family collections|
|When referring collectively to some or all of the species in a genus, we use the generic name followed by 'spp.' (not italicized). |Andropogon spp. |Big bluestem |
|Multiple related genera are gathered into families. Family names start with a capital letter and generally end in “…ceae”. They are not italicized. | Fagaceae |Beech family: includes beeches, oaks, and chestnuts |

: Plant nomenclature rules and conventions. {#tbl-nomenclature_conventions}

The horticultural industry is not always consistent in its use of plant names. And taxonomists, scholars who name plants, regularly re-assign plants to different genera and families as discoveries are made or reassessed. While the XIX International Botanical Congress established naming protocols in its International Code of Nomenclature for algae, fungi, and plants (May et al., 2018), actual listings are still scattered across various scientific journals. In this course we will use the following resources for the authoratative Scientific and Common names:

- USDA, NRCS. (2024). USDA Plants Database. Plants. [https://plants.usda.gov/home](https://plants.usda.gov/home){target="_blank"}
- Rhoads, A. F., & Block, T. A. (2007). The plants of Pennsylvania: An illustrated manual (2nd ed.). University of Pennsylvania Press.
- Dirr, M. A. (2011). Dirr’s Encyclopedia of Trees and Shrubs. Timber Press. 
- Dirr, M. A., & Warren, K. S. (2019). The tree book: Superior selections for landscapes, streetscapes, and gardens. Timber Press.
- Department of Conservation and Natural Resources, Pennsylvania State Game Commission, Pennsylvania State Fish and Boat Commission, & Western Pennsylvania Conservancy. (2019). Plant Communities of Pennsylvania. [https://www.naturalheritage.state.pa.us/Communities.aspx](https://www.naturalheritage.state.pa.us/Communities.aspx){target="_blank"}

Remember, if we encounter derogatory common names in the plants we're considering, we should use inclusive alternatives, as discussed in @sec-dei.

## Planterly, Cultural, and Professional Diversity {#sec-dei}
There's a growing body of scholarship that modern students are learning less and less about plants and plant communities, which are the foundation of sustainable human societies and a big part of what we envision when we think of the beauty of the natural world (Wandersee & Schussler, 1999). We hope this course plays a role in ensuring that the next generation of landscape architects is **nature-literate** and that our profession helps **reverse broader societal trends** toward **plant blindness** and **biodiversity collapse** (Brzuszek et al., 2011; Griswold, 1994; Sturtevant, 1927; Weller, 2014).

<figure>
    <iframe width=100% height="400" src="https://www.youtube.com/embed/cVsI1M_zFMs?si=WqIvN6oYKmXOQbpb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    <figcaption>Doug Tallamy 2024: "WHAT'S THE RUSH to plant natives?" Source: Bringing Back the Natives Garden Tour</figcaption>
</figure>

The gardenesque, culinary, and medicinal uses of plants have underpinned many distinct cultures and traditions across diverse societies, not just amongst privileged classes of European background. We hope this course provides an opportunity to explore the close links between horticulture and human culture, particularly in underappreciated black and brown communities. George Washington Carver (c. 1864-1943) was one of the most prominent botanists of the early 20th century, having discovered hundreds of uses for native and introduced plants across the U.S. David Augustus Williston (1868-1962) was an esteemed landscape architect and horticulturist on many important U.S. campus design projects. More recently, many minority-led design firms have been pushing the boundaries of planting design and methods in contemporary landscape architecture. We think of the outstanding work on the Highline plantings by Isabel Castilla of James Corner Field Operations; the many culturally attuned and inclusive landscapes by Walter Hood and company; José Almiñana's work with Andropogon on Phipps Conservatory's Center for Sustainability, and the award-winning projects of New York-based garden designer, Wambui Ippolito. The list could go on. Throughout the semester, let's look for opportunities to embrace human and professional diversity associated with planting design and methods.

Often, landscape architects describe an invasive species as if it were the source country’s fault; this approach can be hurtful until the conversation becomes more thoughtful and acknowledges that species invasions occur in both directions. For example, Black locust, a native tree species in the northeast U.S., is quite invasive in parts of Europe (I could cite many others). We should scrutinize botanical terminology with negative connotations to support our College's diversity, equity, and inclusion (DEI) policies. Let's begin by embracing Penn State Arboretum's position on the issue:

> "Derogatory Terminology in Common Names and Taxonomy: The fields of botany and horticulture \[and landscape architecture\] have not been immune to the biases and prejudices of the larger culture. This sad and frustrating fact becomes immediately evident when we are confronted with blatantly racist or pejorative common names for plants. Such pejorative terminology is inconsistent with Penn State's values and the professional standards of the public horticulture field. The Arboretum at Penn State \[and us in Larch 245\] will not knowingly use or promote derogatory, biased, or racist common names in any of its publications or educational materials."
>
> -   \*Penn State Arboretum (Citation Unknown)

## Additional Resources

### Botanical and Horticultural Term References
As guides for choosing the appropriate words and descriptions, reference these three PDF files: i) [Leaf and Tree Forms, Patterns, and Parts](https://pennstateoffice365-my.sharepoint.com/:b:/g/personal/tlf159_psu_edu/IQAa7JH7mr8JQpvwg7tDPaeGAbpV98qAqbbuPNxLcxkM8Cw?e=Ur0Gle), ii) [External Form of a Woody Twig](https://pennstateoffice365-my.sharepoint.com/:b:/g/personal/tlf159_psu_edu/IQAGeqmlnpC3TIe3E_eicyJwAc32GdumM6zRFlFVqJaTwlg?e=7gUojA), and iii) [Glossary of Botanical and Horticultural Terms](https://pennstateoffice365-my.sharepoint.com/:b:/g/personal/tlf159_psu_edu/IQDj0zvnIyzgSZfNDT_dNQjhAbp9mK0nlNNQ6RBMcINSXLc?e=f7V2Yb).

::: {.callout-tip}
## Hint

The botanical information noted in this section will be a core part of projects submitted in all plant related courses because clear and accurate communication of plant names is critical to ensure your designs are implemented correctly
::: 

### Other Plant Nomenclature Resources

- The Arnold Arboretum. (2024). Plants. Arnold Arboretum Plants. [https://arboretum.harvard.edu/plants/](https://arboretum.harvard.edu/plants/){target="_blank"}
- The Morton Arboretum. (2024). Trees and Plants. The Morton Arboretum. [https://mortonarb.org/plant-and-protect/trees-and-plants/](https://mortonarb.org/plant-and-protect/trees-and-plants/){target="_blank"}
- The National Gardening Association. (2024). Plants Database. [https://garden.org/plants/](https://garden.org/plants/){target="_blank"}
- The University of Connecticut. (2024). Plant Database. College of Agriculture, Health and Natural Resources. [https://plantdatabase.uconn.edu/](https://plantdatabase.uconn.edu/){target="_blank"}
- USDA. (2024). USDA Plants Database Plant Profile. Plant Profile. [https://plants.usda.gov/home/plantProfile?symbol=amca4](https://plants.usda.gov/home/plantProfile?symbol=amca4){target="_blanks"}

### Field Guide, Plant Identification, and Planting Design References
The following resources are incredibly helpful for identifying plants or choosing plants for your designs. I have copies of all of them; I find them very important. However, note that none need to be purchased for this course, as they are available through Penn State’s library system. 

- Chamberlain, S. 2018. Field guide to grasses of the Mid-Atlantic. 
- Darke, R. 2007. The American woodland garden: Capturing the spirit of the deciduous forest.
- Chamberlain, S. (2018). Field guide to grasses of the mid-Atlantic. Penn State Press.
- Elliott, J. (2003). The American Woodland Garden: Capturing the Spirit of the Deciduous Forest. Northeastern Naturalist, 10(1), 109.
- Haywood, M. J., Monk, P. T., & Botanical Society of Western Pennsylvania. (2001). Wildflowers of Pennsylvania. Venture Graphics Incorporated. 
- Leopold, D. J. (2005). Native Plants of the Northeast: A Guide for Gardening & Conservation. Timber Press.
- Peterson, R. T., McKenny, M., National Audubon Society, National Wildlife Federation, & Roger Tory Peterson Institute. (1996). A Field Guide to Wildflowers: Northeastern and North-central North America. Houghton Mifflin. 
- Tallamy, D. W., & Darke, R. (2009). Bringing Nature Home: How You Can Sustain Wildlife with Native Plants, Updated and Expanded. Timber Press.